KEYCHRON_OPENRGB_PATH := keyboards/keychron/common
KEYCHRON_OPENRGB_TESTS := $(KEYCHRON_OPENRGB_PATH)/tests

openrgb_keychron_DEFS := \
	-DRAW_EPSIZE=64 \
	-DRGB_MATRIX_LED_COUNT=84 \
	-DMATRIX_ROWS=6 \
	-DMATRIX_COLS=16 \
	-DVENDOR_ID=0x3434 \
	-DOPENRGB_ENABLE \
	-DENABLE_RGB_MATRIX_ALPHAS_MODS \
	-DENABLE_RGB_MATRIX_GRADIENT_UP_DOWN \
	-DENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT \
	-DENABLE_RGB_MATRIX_BREATHING \
	-DENABLE_RGB_MATRIX_BAND_SAT \
	-DENABLE_RGB_MATRIX_BAND_VAL \
	-DENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT \
	-DENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL \
	-DENABLE_RGB_MATRIX_BAND_SPIRAL_SAT \
	-DENABLE_RGB_MATRIX_BAND_SPIRAL_VAL \
	-DENABLE_RGB_MATRIX_CYCLE_ALL \
	-DENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT \
	-DENABLE_RGB_MATRIX_CYCLE_UP_DOWN \
	-DENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON \
	-DENABLE_RGB_MATRIX_CYCLE_OUT_IN \
	-DENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL \
	-DENABLE_RGB_MATRIX_CYCLE_PINWHEEL \
	-DENABLE_RGB_MATRIX_CYCLE_SPIRAL \
	-DENABLE_RGB_MATRIX_DUAL_BEACON \
	-DENABLE_RGB_MATRIX_RAINBOW_BEACON \
	-DENABLE_RGB_MATRIX_RAINBOW_PINWHEELS \
	-DENABLE_RGB_MATRIX_RAINDROPS \
	-DENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS \
	-DENABLE_RGB_MATRIX_HUE_BREATHING \
	-DENABLE_RGB_MATRIX_HUE_PENDULUM \
	-DENABLE_RGB_MATRIX_HUE_WAVE \
	-DENABLE_RGB_MATRIX_TYPING_HEATMAP \
	-DENABLE_RGB_MATRIX_DIGITAL_RAIN \
	-DENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE \
	-DENABLE_RGB_MATRIX_SOLID_REACTIVE \
	-DENABLE_RGB_MATRIX_SPLASH \
	-DENABLE_RGB_MATRIX_SOLID_SPLASH

openrgb_keychron_SRC := \
	$(KEYCHRON_OPENRGB_PATH)/openrgb.c \
	$(KEYCHRON_OPENRGB_TESTS)/openrgb_test_mocks.cpp \
	$(KEYCHRON_OPENRGB_TESTS)/openrgb_mapping.cpp

# mocks/ must come FIRST so the shadow headers (quantum.h, color.h, raw_hid.h,
# usb_descriptor.h, version.h, keymap_introspection.h, keychron_raw_hid.h) shadow
# the real QMK headers; the second entry exposes the real openrgb.h under test and
# the recorder header.
openrgb_keychron_INC := \
	$(KEYCHRON_OPENRGB_TESTS)/mocks \
	$(KEYCHRON_OPENRGB_TESTS) \
	$(KEYCHRON_OPENRGB_PATH)
